# The base URL of the site; the only required configuration variable
base_url = "https://paveloom-o.github.io/IDs"

# The site title and description; used in feeds by default
title = "IDs: an identities collection"
description = """\
This website lists identities (characters from movies, series, etc.),\
which one can use for identification (psychological process)."""

# The default language; used in feeds.
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# When set to "true", the generated HTML files are minified
minify_html = true

# Configuration of the Markdown rendering
[markdown]

# Whether external links are to be opened in a new tab
external_links_target_blank = false

# Whether to set rel="nofollow" for all external links
external_links_no_follow = true

# Whether to set rel="noreferrer" for all external links
external_links_no_referrer = true

# Whether smart punctuation is enabled (changing quotes, dashes, dots in their typographic form)
# For example, `...` into `…`, `"quote"` into `“curly”` etc
smart_punctuation = true

# Custom variables
[extra]
author = "Pavel Sobolev"
