name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  BuildAndDeploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Build the site
        run: .github/scripts/build.bash https://paveloom.github.io/
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: public
          single-commit: true
